### ISSUE TITLE
Move to 2 or 3 slide on next button click

### ISSUE THREAD

**Issue by anupgusain** [rcbyr/keen-slider#130]
Can any one guide me how can I move 2-3 slide at a time on next or previous button click

**Comment by cainmagi** [comment]
This feature is easy to implement. For example, instead of using `slider.prev()` like this

```jsx
<ArrowLeft
  onClick={(e) => e.stopPropagation() || slider.prev()}
  disabled={false} //{currentSlide === 0}
/>
```

, you could use the following example:

```jsx
<ArrowLeft
  onClick={(e) => e.stopPropagation() || slider.moveToSlide(slider.details().absoluteSlide - 2)}
  disabled={false} //{currentSlide === 0}
/>
```

For the `slider.next()` case, you only need to replace `- 2` by `+ 2`.

**Comment by yuraavakyan** [comment]
@cainmagi Is there any way to detect direction of dragging and accordingly changemultiple  slides to the left or to the right?

**Comment by cainmagi** [comment]
> @cainmagi Is there any way to detect direction of dragging and accordingly changemultiple slides to the left or to the right?

Actually, I have not worked on React for a little bit long, so I do not thinks I can give you an exact solution.

To my knowledge, if I were you, I would prefer to merge these "multiple slides" into one slide rather than hooking the dragging event. Overriding the dragging event may not give you what you exactly want. For example, in the guide:
https://keen-slider.io/docs#event-hooks

It says that `dragStarted` and `dragEnded` can let to detect whether a dragging event begins or ends. `dragChecked` can let you know what direction is of this dragging event. I have not tried to test them, but I think using these features cannot let you control the behavior at the middle point of the dragging event. That sounds problematic to me. So I think "merging" the multiple slides as one may be a better choice.

**Comment by yuraavakyan** [comment]
@cainmagi Thank you so much, I couldn't think of a way to use multiple slides as one slide. Thank you!
