### ISSUE TITLE
TypeError: instance.details is not a function

### ISSUE THREAD

**Issue by kostas-artware** [rcbyr/keen-slider#158]
Hello Everyone,

The sliders in all of my site stopped working all of a sudden.

I tried to find the reason but all I get in the console is TypeError: instance.details is not a function

`TypeError: instance.details is not a function
    at updateClasses ((index):1090)
    at created ((index):1082)
    at Object.emit (keen-slider.js:1)
    at keen-slider.js:1
    at n.first (keen-slider.js:1)
    at new <anonymous> (keen-slider.js:1)
    at (index):1060
(anonymous) @ keen-slider.js:1
`

Could someone please give a help?

**Comment by rcbyr** [comment]
Hello @kostas-artware 

you have probably updated the slider to the new version v6.*. Since there are some changes in the API (some option and method names have changed), you will also need to update your functions. For the concrete error, you need to change `instance.details()` to `instance.track.details`.

**Comment by kostas-artware** [comment]
Great,
Thanks a lot for your help.

**Comment by rcbyr** [comment]
The details-object has also changed a bit. You can find the old documentation (here)[https://keen-slider.io/docs/v5] and the new one (here)[https://keen-slider.io/docs]. 

You can also stay by the former version 5.
