### ISSUE TITLE
Transform scale 2 or 3 width of slides

### ISSUE THREAD

**Issue by morteyxyz** [rcbyr/keen-slider#175]
HI
I create slider in angular project and I problem in scale o trasform .
My device width 360px but translate 720px

![image](https://user-images.githubusercontent.com/15963711/145794973-c384dbda-a2bc-4959-8e23-386117dd2a47.png)

`this.slider = new KeenSlider(this.sliderRef.nativeElement, {
        initial: 0,
        loop: false,
        rtl: true,
        slides: {perView: 1},
        slideChanged: (s) => {
          console.log(s)
          this.currentSlide = s.track.details.abs;
          console.log(this.currentSlide)
        },
      })`
      please help me @rcbyr

**Comment by rcbyr** [comment]
Hey @morteyxyz 

I am a little confused as to what the problem is. The width of your device is 360px, just like the min-width and max-width of a slide. translate3d(x,0,0) refers to the position of the slides on the x-axis. For the second slide it is -720px. This is correct in terms of its options and slide width. Can you describe your problem a little bit more?
