### ISSUE TITLE
More than one slide per view and spacing, resize issue

### ISSUE THREAD

**Issue by mikael9i** [rcbyr/keen-slider#181]
With for example that configuration(React + TS):
```
 slides: {
            perView: 3,
            spacing: 24,
        },
```
I have strange behavior when I resized window, how I can avoid that changing of  `slider.track.details.rel`, because it is impossible to disable right button and set proper active dot. 

https://user-images.githubusercontent.com/5570948/148181600-f6647909-c882-4881-8093-cd40b377782d.mp4

**Comment by ponciusz** [comment]
I noticed it as well same issue but happens when last slide is active then its breaking controls:

in my case its re-rendering slider when I am on last slide because slider.track.details.rel is recalculated and sometimes its wrong (broken scenario) / and slider works fine when value is calculated correctly.

https://codesandbox.io/s/awesome-orla-rzqhej?file=/src/App.js

https://user-images.githubusercontent.com/3374777/155369427-f3a49288-615c-4992-b424-86f497f2baad.mp4

**Comment by ponciusz** [comment]
I was digging little bit and figured out a way to fix it:

I was not checking side effects but issue is gone.

<img width="554" alt="Screenshot 2022-03-02 at 21 02 34" src="https://user-images.githubusercontent.com/3374777/156449303-fdb359cf-a78c-4b27-a1f7-60c287778f1d.png">

**Comment by ponciusz** [comment]
@rcbyr  I fixed the issue how I can create merge request??
problem was in `getIndexes` function,
const `positionRelative` sometimes had 6 digits after coma sometimes more so `reduce` function was producing false results.

https://github.com/ponciusz/keen-slider/commit/f32820b24d80533dcf95157c37dbf70ad1c37940

**Comment by rcbyr** [comment]
Seems to be fixed by the PR from ponciusz.
