### ISSUE TITLE
multiple slides perView makes an empty space

### ISSUE THREAD

**Issue by ramtinattar** [rcbyr/keen-slider#223]
Hey there,
I'm facing an issue with PerView value. When I want to show more than one slide ( for example 3 ) and I use perView: 3, there is a big empty space in the end of the slider. And the number of dots is still as much as when we have one slide per view.
For example if I have 6 slides and I wanna have 3 per view, instead of having 2 dots I still have 6.

Could you fix these 2 issues or if there is a solution already could you give me a hint ?

Thanks,
Ramtin

**Comment by rcbyr** [comment]
Hey @ramtinattar 

can you share your code or better create a codesandbox. Which version do you use?

**Comment by ramtinattar** [comment]
Hey @rcbyr 

Here an example of what I'm talking about : https://codesandbox.io/s/frosty-boyd-058vf9?file=/index.html:1030-1033

**Comment by rcbyr** [comment]
Hey @ramtinattar 

thank you very much for creating the codesandbox. The origin property sets the origin(halt point) of all slides and this relative to the viewport. Because of that you this big empty space at the end of the slider. Because the halt point of the last slide is at 0.1. -> I've adjust your codexample. https://codesandbox.io/s/relaxed-antonelli-0wmwur?file=/index.html

The problem with the number of points is/was discussed here. https://github.com/rcbyr/keen-slider/issues/55
