### ISSUE TITLE
How to set the center slide as active

### ISSUE THREAD

**Issue by RigottiG** [rcbyr/keen-slider#236]
I'm facing an issue, I want to set the slide in the center as `active`, but the default is left. How can I set the center slide to 'active' so that I can apply some styles to it?

I need the center slide to be bigger than the others, I thought about using a `transform: scale(1.5)` but I think Keen Slider already applies a transform so it won't work, any idea ?

![image](https://user-images.githubusercontent.com/13246770/171466238-30daa8f9-207f-4df3-8283-87e7b9096593.png)

**Comment by DuyguKeskek** [comment]
Hi @RigottiG, could you find a solution for that? I had the same issue with you and found a similar example here: https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/media/zoom-out/javascript?file=/index.html:1479-1482

However, I still don't know how to get the visible centered slide. I could get the centered slide by using `slides[idx].distance`  but it's not the most ideal way to do that. Do you have any idea?
Maybe @rcbyr can help us on that :) I don't see any option rather than `origin: 'center'`. I am trying to add a class to the centered slide.

Thanks!
