### ISSUE TITLE
Suggestion - Plug-able mode option

### ISSUE THREAD

**Issue by roderickhsiao** [rcbyr/keen-slider#30]
Thanks for the awesome library.

One suggestion here is for the `mode` option, 

```javascript
function moveWithSpeed() {
    hook('beforeChange')
    switch (options.mode) {
      case 'free':
        moveFree()
        break
      case 'free-snap':
        moveSnapFree()
        break
      case 'snap':
      default:
        moveSnapOne()
        break
    }
  }
```

wondering if we can make it pluggable so only the default one will be built in, and the library could export other mode such as

```js
import { freesnap }, KeenSlider from 'keen-slider';

const slider = new KeenSlider('#my-slider', {
  loop: true,
  modeFunc: freesnap
});
```

In this case its easier to tree-shake methods the people are not using it and reduce the overall bundle size.
It might not be totally easy to implement without refactor as most of the function are written accessing global variable, just throwing some idea to make the library more flexible.

Cheers

**Comment by rcbyr** [comment]
Hey @roderickhsiao 

thank you very much! 

I like the idea of making the library more modular. I'm hoping to have some time over the next weeks to refactor the whole movement and animation part. I think I can get a lot more out of it and will definitely consider your suggestion. 

Since I want the slider available for react-native, I have to make some more changes anyway.

**Comment by jayphelps** [comment]
@rcbyr is there still appetite for this? We'd be willing to contribute a PR if so.
