### ISSUE TITLE
internal "hooks" internal references do not update if external data updates

### ISSUE THREAD

**Issue by dualcyclone** [rcbyr/keen-slider#42]
See console output from this example: https://codesandbox.io/s/keen-slider-hooks-issue-9yneh?file=/src/App.js

When I navigate between slides, `slideChanged` will update the state value for `currentSlide` with the sliders relative slide.

`dragEnd` is called momentarily before `slideChanged`, and will output the sliders relative slide, and the state value for `currentSlide`

However, even when `currentSlide` is updated, the internal hook hangs on to the old value as seen in the console output:

```
****** currentSlide 0
****** currentSlide 0
***** slideChanged - relativeSlide 0 currentSlide 0
****** currentSlide 0
****** currentSlide 0
***** dragEnd - relativeSlide 0 currentSlide 0
***** slideChanged - relativeSlide 1 currentSlide 0
****** currentSlide 1
****** currentSlide 1
***** slideChanged - relativeSlide 2 currentSlide 0
****** currentSlide 2
****** currentSlide 2
***** dragEnd - relativeSlide 2 currentSlide 0
***** slideChanged - relativeSlide 3 currentSlide 0
****** currentSlide 3
****** currentSlide 3
***** dragEnd - relativeSlide 3 currentSlide 0
***** slideChanged - relativeSlide 4 currentSlide 0
****** currentSlide 4
****** currentSlide 4
***** dragEnd - relativeSlide 4 currentSlide 0
***** slideChanged - relativeSlide 5 currentSlide 0
****** currentSlide 5
****** currentSlide 5
***** dragEnd - relativeSlide 5 currentSlide 0
```

Seems like a scoping issue

**Comment by rcbyr** [comment]
Hello @dualcyclone 

I understand the problem and it makes perfect sense that this doesn't work at the moment. I need to extend the hook and slide to make this work. I will add this to my list, but it is not my top priority because it is easy to avoid this problem. If you have a problem with a concrete implementation, let me know.

**Comment by apacholik** [comment]
Hi @rcbyr ,

We use slider in our project and too have problem wit this case.

Wee need lazy load, and We do it this way: https://codesandbox.io/s/frosty-lederberg-oev7b. Ofc. `loaded` state is all time initial.

I don't understand why You in [example](https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/master/media/lazy-load/react?file=/src/App.js) use useEffect. Now I know.

This is silent error :(

**Comment by ufon** [comment]
This happens because, in useKeenSlider hook, `useEffect` only reinitialize slider when found different [options object](https://github.com/rcbyr/keen-slider/blob/master/src/react.js#L25). KeenSlider instance also has a `refresh` method and we can trigger it when we want new data from the component.

For example, here I need reinitialization when I get new items. I also need a force update in `afterChange` event, because in the `dragEnd` event I changed the component state. And I need a new state in the next `dragEnd` event. To avoid unnecessary rerenders I used `useRef` hook.

```js
  const [, updateState] = useState<object>()
  const forceUpdate = useCallback(() => updateState({}), [])

  const [sliderRef, slider] = useKeenSlider({
    initial: 0,
    slidesPerView,
    dragEnd: onDragEnd,
    afterChange: forceUpdate,
    ...(spacing && { spacing }),
  })

  useDeepCompareEffect(() => {
    slider?.refresh()
  }, [items, slidesPerView])
```

A possible fix can be to improve useKeenSlider useEffect and reinitialize it if the component state changes. We can achieve this behavior by refresh on every render:

```js
  useEffect(() => {
    slider?.refresh()
  })
```

But this causes a weird reinitialization and animation, especially if you have re-render action on dragEnd event.

**Comment by rcbyr** [comment]
I've looked at this problem again. The best solution is to use reference if you need some changing values within the event hooks. This will cause no rerenderings at all.  I've updated your example. https://codesandbox.io/s/keen-slider-hooks-issue-forked-67i3e?file=/src/App.js
