### ISSUE TITLE
Bug?: Slidechanged event is delayed, when using dot-values in slidesPerView

### ISSUE THREAD

**Issue by stefanbayjensen** [rcbyr/keen-slider#49]
**I don't know if this is a bug, or a feature request**
I've noticed, that the slideChanged event, is slightly delayed, when using a dot-value in slidesPerView – I've been able yo replicate it, with the following example:

```js
import "./styles.css";
import "keen-slider/keen-slider.min.css";
import KeenSlider from "keen-slider";

const slider = new KeenSlider("#my-keen-slider", {
  slidesPerView: 2.5,
  slideChanged: (instance) => {
    console.log("slideChanged");
  }
});

const next = document.querySelector("[data-next]");

next.addEventListener("click", () => slider.next());
```

**Comment by rcbyr** [comment]
Hello @stefanbayjensen 

it is not a bug but maybe a missing feature. Currently no internal slide index is set by calling next() or moveToSlide(idx). Instead, a distance is defined that must be moved to get to this index. During movement, the slider checks which slide is closest to the origin point. What is in your case, the left side of the viewport. I hope this is understandable.

Currently, the only way to get the index immediately is to modify the index outside the slider and use moveToSlide instead of next.

But I add a feature for this, in the next big update. (in a couple of weeks/months)

**Comment by rcbyr** [comment]
I have added this function in the new major version. At each next, moveToIdx or dragEnd the `animationStarted` event is fired. At this time the targetIdx of the animation is set and can be used as the next active index. You can find an implementation here: https://keen-slider.io/examples#thumbnails
