### ISSUE TITLE
 Is there a VUE version?

### ISSUE THREAD

**Issue by w-danboard** [rcbyr/keen-slider#77]
Is there a VUE version?

**Comment by ruijdacd** [comment]
Hello @w-danboard, the package itself is library agnostic, so there isn't any direct connection to any framework/library, with that being said, there is a react hook `useKeenSlider` along with the library core.

Currently there isn't anything similar for VueJS, and I'm not entirely sure if there are plans to implement it.

However since the library is completely agnostic to any library/framework, it can be easily used together with other frameworks such as VueJS.

On the [examples page](https://keen-slider.io/examples/#examples), each example has a version built-in for the most popular frameworks. I would suggest you, to use them as a starting point and perhaps even contribute to the package with some VueJS (or other frameworks) components/patterns to simplify the usage for other developers.

Hope I answered your question.
Have a great day! 👋

**Comment by TheNoim** [comment]
If you don't want to code your own wrapper, you could use my one: https://github.com/TheNoim/vue-keen-slider
I am currently using it in production. Or just write your own. It isn't that hard.

**Comment by tkanq** [comment]
Let me share the problem and solution I had, to anyone who want to use keen-slider with vue.

If you have data inside slide elements, make sure to have them fully prepared/loaded before you do new KeenSlider(), otherwise you will have problem.

In my case, this gave me unexpected behavior (sliders not working and layout broken):
```vue
<template>
  <div ref="slider" class="keen-slider">
    <template v-for="page in pages">
      <preview class="keen-slider__slide" :page="page" :key="`${page.albumId}-${page.pageId}`" ></preview>
    </template>
  </div>
</template>

<script>
export default {
  mounted() {
    this.$db.getPages().then(pages => {
      this.pages = pages
    })
    this.slider = new KeenSlider(this.$refs.slider, {
      spacing: 10,
      slidesPerView: 1,
      rtl: true,
    })
  }
}
</script>
```

but this worked:
```vue
<template>
  <div ref="slider" class="keen-slider">
    <template v-for="page in pages">
      <preview class="keen-slider__slide" :page="page" :key="`${page.albumId}-${page.pageId}`" ></preview>
    </template>
  </div>
</template>

<script>
export default {
  async mounted() {
    await this.$db.getPages().then(pages => {
      this.pages = pages
    })
    this.slider = new KeenSlider(this.$refs.slider, {
      spacing: 10,
      slidesPerView: 1,
      rtl: true,
    })
  }
}
</script>
```

I just needed to make getPages() awaited,  but it took me a good 2 or 3 hours to understand what was going on.

**Comment by rcbyr** [comment]
Hello @w-danboard 

the actual version comes with a composition function for Vue3.
