### ISSUE TITLE
Carousel or coverflow effect

### ISSUE THREAD

**Issue by skycult** [rcbyr/keen-slider#79]
Hi there,
this is so amazing! What is the right way to obtain a carousel effect like this:

https://codepen.io/nopr/pen/rfBJx (https://3dtransforms.desandro.com/carousel)

or a coverflow effect like this one?

https://wlada.github.io/vue-carousel-3d/examples/

Thank you!

**Comment by rcbyr** [comment]
Hey @skycult 

thanks for your request. I will create some examples and publish them on the website.

**Comment by rcbyr** [comment]
I created the carousel example. The coverflow is a really custom implementation. Maybe, I will do this sometime in the future.

**Comment by masoudjapalaghi** [comment]
Hi, I tried the coverflow effect with the provided APIs and documentation. Now the only problem is that I need to give a value to "translate3d" so that I can add "scale" to it as well (otherwise apply Scale, translate3d will be overwritten) and also if possible I can apply the 3D value when these items disappear or come in since they are now linear what is your solution for this?? Of course, the code must be modified again.






import React, { useEffect } from "react";
import { useKeenSlider, TrackDetails } from "keen-slider/react";
import "keen-slider/keen-slider.min.css";

const Test: React.FC = () => {
  const [details, setDetails] = React.useState<TrackDetails | null>(null);
  const [sliderRef, instanceRef] = useKeenSlider(
    {
      loop: true,
      // renderMode:"custom",
      slides: {
        origin: "center",
        perView: 5,
        spacing: -90,
      },
      detailsChanged(s: { track: { details: TrackDetails } }) {
        setDetails(s.track.details);
      },

      slideChanged() {
        console.log("slide changed");
      },
    },
    [
      // add plugins here
    ]
  );

  function scaleStyle(idx: number, hasParent?: boolean) {
    if (!details) return {};
    // const details = instanceRef.current?.options.
    const slide = details.slides[idx];
    const scale_size = 0.9;
    const scale = 1 - (scale_size - scale_size * slide.portion);
    const centerItem = details.abs === slide.abs;
    const prevCenterItem = details.abs === slide.abs - 1;
    const nextCenterItem = details.abs === slide.abs + 1;

    if (hasParent) {
      return {
        zIndex: centerItem ? 3 : prevCenterItem || nextCenterItem ? 2 : 1,
      };
    } else if (Math.round(slide.portion) == 1) {
      // cubic-bezier(0.785, 0.135, 0.15, 0.86)
      // cubic-bezier(0.68, -0.55, 0.265, 1.55)
      // cubic-bezier(0.645, 0.045, 0.355, 1)
      // cubic-bezier(0.55, 0.085, 0.68, 0.53)
      return {
        transition: "all .5s cubic-bezier(0.785, 0.135, 0.15, 0.86)",
        transform: `scale(${
          centerItem ? 0.98 : prevCenterItem || nextCenterItem ? 0.9 : 0.8
        })`,
        WebkitTransform: `scale(${
          centerItem ? 0.98 : prevCenterItem || nextCenterItem ? 0.9 : 0.8
        })`,
        // opacity: centerItem ? 1 : prevCenterItem || nextCenterItem ? 0.3 : 0.1,
      };
    }

    return {
      opacity: 0,
      transition: "all .5s cubic-bezier(0.785, 0.135, 0.15, 0.86)",
      transform: `scale(.7) `,
      WebkitTransform: `scale(.7)`,
    };
  }

  return (
    <div style={{ margin: "0 auto" }}>
      <div ref={sliderRef} className="keen-slider zoom-out">
        {images.map((src: string, idx: number) => (
          <div
            key={idx}
            className="keen-slider__slide zoom-out__slide"
            style={scaleStyle(idx, true)}
          >
            <div style={scaleStyle(idx)} className="cart">
              {src}
            </div>
          </div>
        ))}
      </div>
      <div className="navigation">
        <div onClick={() => instanceRef.current?.next()}>next</div>
        <div onClick={() => instanceRef.current?.prev()}>prv</div>
      </div>
      <style jsx>
        {`
          .keen-slider {
            perspective: 100px;
          }
          .keen-slider__slide {
            transform-style: preserve-3d;
          }
          .navigation {
            display: flex;
            justify-content: center;
            gap: 12px;
          }
          .cart {
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 28px;
            min-height: 320px;
            background-color: lightBlue;
            box-shadow: 0px 0px 4px #0f0f0f;
          }
        `}
      </style>
    </div>
  );
};

export default Test;

const images: string[] = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
];
