### ISSUE TITLE
TypeError: Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by baptisteArno** [rcbyr/keen-slider#82]
I'm trying to render the slider conditionally with React.

```tsx
const [inspectionSliderRef, inspectionSlider] = useKeenSlider({
    initial: 0,
    loop: true,
    slideChanged(s) {
      setCurrentSlide(s.details().relativeSlide);
    },
  });

useEffect(() => {
    if (inspectionSlider) inspectionSlider.resize();
  }, [inspectingPhoto]);

return <>{showSlider && (
          <div
            ref={inspectionSliderRef as RefObject<HTMLDivElement>}
            className="keen-slider"
            style={{ height: "100%" }}
          >
[...]
          </div>
      )}</>
```

`inspectionSlider.resize()` throws:

```
Unhandled Runtime Error
TypeError: Cannot read property 'offsetWidth' of undefined
```

What's wrong here?

**Comment by rcbyr** [comment]
Hey @baptisteArno,

the problem is inside the hook. On initialization, ref.current is undefined and is not updated when showSlider becomes true. A quick fix would be to move the showSlider property in the parent component and hide/show the entire component that creates the slider. The long term solution is for me to extend the hook.

**Comment by baptisteArno** [comment]
Thank you @rcbyr. It works perfectly when exporting the slider to a standalone component 💪
